### ISSUE TITLE
Release version of Parsson that supports Jakarta Annotations 3

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/parsson#118]
The current version of Parsson is build against Jakarta Annotations 2.1, and therefore contains a guard in MANIFEST.MF to block versions 3 and higher:

```
Import-Package: jakarta.annotation;version="[2.1,3)"
```

This means Parsson cannot be used in OSGi environments (such as GlassFish, possibly Open Liberty) that provide Jakarta Annotations 3.0.

**Comment by edburns** [comment]
Hello @arjantijms , I believe [parsson-118](https://github.com/eclipse-ee4j/parsson/issues/118) can be closed because the linked PR has been merged. If so, can you please close it? If not, what else must be done?

**Comment by arjantijms** [comment]
The linked PR for GF is just the initial EE 11 support there with a lot of patches (including Parsson).

This commit may have done the trick though: https://github.com/eclipse-ee4j/parsson/commit/c96ef80bb3366caf2abdeb925265afc8646cd19a
