### ISSUE TITLE
Missing UTF-32 charset should fail only in case UTF-32 is detected

### ISSUE THREAD

**Issue by danielkec** [eclipse-ee4j/parsson#121]
Right now UTF-32 chaset is looked up for unicode version detection during class initialization, no matter whether there will be ever any use of it:
https://github.com/eclipse-ee4j/parsson/blob/981cd2f16390e75dedebd55b6519df6c222811a1/impl/src/main/java/org/eclipse/parsson/UnicodeDetectingInputStream.java#L32-L35

Actual lookup should be done lazily when UTF-32 is actually detected to support runtimes without UTF-32, like GraalVM native image oracle/graal/issues/1294

**Comment by Captain1653** [comment]
This issue was fixed in January, but wasn't released as I can see. Is it possible to create the new version with this fix?

**Comment by lukasj** [comment]
@Captain1653 if you have a question, use new issue/mail/discussion post for it
