### ISSUE TITLE
Expected EOF token, but got CURLYOPEN

### ISSUE THREAD

**Issue by hendre73** [eclipse-ee4j/parsson#127]
I am trying to parse a popular dataset from https://musicbrainz.org/. The data set has been in the market for years and I cannot make changed to it. I downloaded the data on Linux using a standard CURL command.

I am getting the following exception:

Exception in thread "main" jakarta.json.stream.JsonParsingException: Expected EOF token, but got CURLYOPEN
	at org.eclipse.parsson.JsonParserImpl.hasNext(JsonParserImpl.java:348)

This is the code I am running

        JsonParser parser = Json.createParser(new FileReader(jsonPath.toFile()));
        while (parser.hasNext()) {
            JsonParser.Event event = parser.next();
        }

Here is a download link to the dataset (34 Meg): https://data.metabrainz.org/pub/musicbrainz/data/json-dumps/20240327-001001/area.tar.xz

**Comment by jbescos** [comment]
It seems that file contains many JSONs. Each line corresponds to a different JSON.

You need to iterate every line of the file and parse it as JSON.
