### ISSUE TITLE
Is 1.1.0 released?

### ISSUE THREAD

**Issue by lmsurpre** [eclipse-ee4j/parsson#59]
I see a 1.1.0 version listed at https://mvnrepository.com/artifact/org.eclipse.parsson/jakarta.json/1.1.0

However, I see no 1.1.0 version at either https://github.com/eclipse-ee4j/parsson/releases or https://projects.eclipse.org/projects/ee4j.parsson

I do see a [1.1.0 tag](https://github.com/eclipse-ee4j/parsson/tree/1.1.0) in the repo, but the github UI says the released commit is not in the repo.  What is going on here?
Can you confirm that 1.1.0 was intentionally released and comment on whether this is how we should expect releases to be posted?

**Comment by bjhargrave** [comment]
> I do see a [1.1.0 tag](https://github.com/eclipse-ee4j/parsson/tree/1.1.0) in the repo, but the github UI says the released commit is not in the repo.

That is not what github says. It just says that the tag is not associated with any branch in the repo and this is quite normal. You can clone the repo and create your own branch from the tag.

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.


> However, I see no 1.1.0 version at either https://github.com/eclipse-ee4j/parsson/releases

I don't think there is a requirement to use github releases. The tag is the important thing.

> or https://projects.eclipse.org/projects/ee4j.parsson

Yes, the project should have created a release record in the Eclipse management system.

**Comment by lmsurpre** [comment]
Thanks BJ.  Looks like the 1.1.0 tag came from `1.1.0-RELEASE` which got deleted when https://github.com/eclipse-ee4j/parsson/pull/54 got merged.  It will be good to have the Eclipse record updated sooner than later, but my concerns are addressed.
