### ISSUE TITLE
jakarta.json-1.1.0 ships with JSON API incompatible with 2.1.0

### ISSUE THREAD

**Issue by pdudits** [eclipse-ee4j/parsson#60]
Version 1.1.0 released to central on January 21st does not ship with final JSON API 2.1.0, which was released on March 9th, despite exporting the package.

Chiefly it doesn't include https://github.com/eclipse-ee4j/jsonp/commit/8d210fa988df7b64cd3fa3feb1251180ad8dca7f, which changes `JsonProvider.JSONP_PROVIDER_FACTORY` to public, and therefore fails signature tests.

Since 1.1.0 on central surely does not correspond to commit 0bce403 as one would expect, best course of action would be to release 1.1.1 as soon as possible.

**Comment by lukasj** [comment]
fixed in 1.1.1
