### ISSUE TITLE
Parsson media do not work with injection framework on module path

### ISSUE THREAD

**Issue by tomas-langer** [eclipse-ee4j/parsson#61]
When I run Weld + Jersey + Parsson on module path, I get the following exception:
```
java.lang.reflect.InaccessibleObjectException: Unable to make private void org.eclipse.parsson.media.JsonValueBodyWriter.init() accessible: module org.eclipse.parsson.media does not "opens org.eclipse.parsson.media" to module weld.core.impl
```

As the `init` method annotated with `@PostConstruct` is private, we need to have it open for injection frameworks, as otherwise this cannot be called. 

Please either change the method to `public` or open the package.

Thank you.

**Comment by lukasj** [comment]
injection frameworks should define requirements for this to work, like ie CDI should say sth like _annotated methods needs to be open to at least jakarta.enterprise.cdi_ and be able to take it from there. Explicitly opening the package to particular implementation is closing doors for working with other implementations, while opening it for everyone is just too much.

all in all, making the method public sounds like the only solution for now

**Comment by jansupol** [comment]
Reopening as the bug is against Parsson 1.0.0.

**Comment by jansupol** [comment]
It is a problem in master, too. Both versions have the problem.

**Comment by tomas-langer** [comment]
I am using version 1.1.0 - I would need to get it fixed in that major version

**Comment by jansupol** [comment]
@tomas-langer  Parsson 1.1.0 is EE 10 parsson. Are you sure you are using 1.1.0?

**Comment by lukasj** [comment]
since API 2.1.x is backwards compatible with 2.0.x and Parsson 1.1.x is backward compatible with 1.0.x I see no point being stuck at 2.0.x/1.0.x unless there is strong reason for the older version
